[pytest]
addopts = -q
pythonpath = . src
testpaths = tests

markers =
    admin: testes da área administrativa (CRUD de produtos)
    cadastro: testes de cadastro/login/logout de cliente
    checkout: testes de checkout de cliente