[pytest]
pythonpath =
    src

testpaths =
    src/tests
    ADMIN-CRUD-Produto/tests
    Checkout-Cliente/tests
    cadastro-login-logout/tests


asyncio_mode = strict

addopts = -ra --junitxml=reports/junit/results.xml

markers =
    e2e: testes end-to-end que cobrem fluxo completo do usuário/sistema